const LABELS: Record<string, string> = {
	id: "Identificador",
	number: "Número",
	title: "Título",
	name: "Nombre",
	description: "Descripción",
	text: "Texto",
	slug: "Enlace de la noticia",
	owner_id: "Cuenta propietaria",
	author: "Firma / autor",
	status: "Estado",
	category: "Categoría",
	published_on: "Fecha de publicación",
	date_label: "Fecha visible (opcional)",
	summary: "Resumen",
	body_markdown: "Contenido Markdown",
	sort_order: "Posición",
	href: "Destino del enlace",
	link_label: "Texto del enlace",
	image_alt: "Texto alternativo",
	asset_key: "Imagen incluida (respaldo)",
	media_id: "Imagen de la biblioteca",
	content_id: "Página",
	role: "Cargo",
	contact: "Contacto",
	email: "Correo electrónico",
	full_name: "Nombre completo",
	institution: "Institución",
	subject: "Asunto",
	message: "Mensaje",
	edition_year: "Año de la edición",
	is_current: "Edición actual",
	announcement: "Anuncio",
	starts_on: "Fecha inicial",
	ends_on: "Fecha final",
	national_olympiad_id: "Edición nacional",
	sponsor_id: "Patrocinador",
	team_member_id: "Miembro del equipo",
	card_number: "Tarjeta de valores",
	page_key: "Página de destino",
	placement: "Ubicación",
	label: "Etiqueta",
	icon: "Icono",
	icon_path: "Trazado del icono",
	brand_key: "Red social",
	emphasis: "Resaltar",
};
const WORDS: Record<string, string> = {
	seo: "SEO",
	title: "título",
	description: "descripción",
	intro: "introducción",
	eyebrow: "antetítulo",
	hero: "portada",
	highlight: "texto destacado",
	image: "imagen",
	alt: "texto alternativo",
	media: "medio",
	id: "identificador",
	about: "nosotros",
	national: "nacionales",
	olympiad: "olimpiada",
	link: "enlace",
	href: "destino",
	label: "etiqueta",
	sponsor: "patrocinadores",
	facts: "datos",
	follow: "redes",
	contact: "contacto",
	email: "correo",
	heading: "encabezado",
	card: "tarjeta",
	form: "formulario",
	required: "obligatorio",
	notice: "aviso",
	before: "antes",
	after: "después",
	invalid: "inválido",
	fields: "campos",
	full: "completo",
	name: "nombre",
	placeholder: "ejemplo",
	institution: "institución",
	subject: "asunto",
	message: "mensaje",
	help: "ayuda",
	submit: "enviar",
	pending: "enviando",
	success: "éxito",
	section: "sección",
	alert: "aviso",
	labor: "labor",
	members: "miembros",
	team: "equipo",
	information: "información",
	registration: "inscripción",
	levels: "niveles",
	preparation: "preparación",
	prizes: "premios",
	awards: "premiación",
	video: "video",
	sponsors: "patrocinadores",
};
export function field_label(name: string) {
	return (
		LABELS[name] ??
		name
			.split("_")
			.map((word) => WORDS[word] ?? word)
			.join(" · ")
	);
}
